### PR TITLE
fix: tab label priority. label -> name -> attribute

### LINKED ISSUE #101: fix: tabs (sidebar) only uses "entity.name" for tabs text
Screenshot_20230228_151013

Steps to reproduce:
- display any entity with the "tabs" plugin in sidebar configuration where the child entities does not have a "name" attribute

Expected behavior:
- "tabs" should use the attribute name from the parent as fallback if the child entity does not have a label or name
  - `entity.label ?? beautify(entity.name) ?? attribute.name`

### PR DESCRIPTION
**Pull request by soofstad**
## What does this pull request change?
- "tabs" plugin label text now has fallback values if the entity does not have a "name"-attribute

## Why is this pull request needed?
see #101 

## Issues related to this change
closes #101

### CODE REVIEW

File: packages/dm-core-plugins/src/tabs/Tabs.tsx [hunk 1]
```diff
@@ -62,7 +65,9 @@ export const Tabs = (): JSX.Element => {
             onClick={() => setSelectedTab(tabData.attribute)}
             active={selectedTab === tabData.attribute}
           >
-            {tabData.entity.name}
+            {tabData.entity?.label ??
+              prettifyName(tabData.entity?.name || '') ??
+              selectedTab}
```
Comment (ingeridhellen) [inline packages/dm-core-plugins/src/tabs/Tabs.tsx:70]: shouldn't it be 
```suggestion
              tabData.entity?.attribute}
```
?

**Review by KristianKjerstad — APPROVED** [review]
looks good! assuming other requested changes are implemented

**Review by eoaksnes — APPROVED** [review]

File: packages/dm-core-plugins/src/tabs/Tabs.tsx (hunk 1 above)
Comment (soofstad) [reply packages/dm-core-plugins/src/tabs/Tabs.tsx:70]: It should!

**Review by ingeridhellen — APPROVED** [review]
