### PR TITLE
fix: bug when saving optional value in form plugin

### LINKED ISSUE #146: bug(form): saves unedited optional values as strings
If you open an entity in "form" which has an optional number value, and save it without editing that value. It will be created as a string.

### PR DESCRIPTION
**Pull request by KristianKjerstad**
## What does this pull request change?
fix bug in form:

bug:
1) update an optional text field (for example `aOptionalNumber` in FormExample.json)
2) save
3) update the same text field:  delete the content of `aOptionalNumber` textfield
4) save

After these steps, the document in the database has an empty string stored in the `aOptionalNumber` attribute. 
There are 2 things wrong with this:
1) even though type is a number, the saved value is a string
2) the attribute should not even be saved in the document

The correct behavior is to remove the attribute from the document.
## Issues related to this change
closes #146

### CODE REVIEW

**Comment by KristianKjerstad** [comment]
TODO - pair programming to fix test failure

File: packages/dm-core-plugins/src/form/fields/NumberField.tsx [hunk 1]
```diff
@@ -47,19 +47,24 @@ export const NumberField = (props: TNumberFieldProps) => {
         required: !optional,
         pattern: { value: /^[0-9]+$/g, message: 'Only digits allowed' },
       }}
-      defaultValue={defaultValue || undefined}
+      defaultValue={defaultValue || null}
```
Comment (KristianKjerstad) [inline packages/dm-core-plugins/src/form/fields/NumberField.tsx:50]: react-hook-form does not allow undefined as a value
https://react-hook-form.com/api/usecontroller/controller/

File: packages/dm-core-plugins/src/form/fields/NumberField.test.tsx [hunk 2]
```diff
@@ -169,5 +169,60 @@ describe('NumberField', () => {
...
+          ],
+        },
+      ])
+      let value = 567
+
+      const formData = {
+        foo: value,
+      }
+
+      const { container } = render(
```
Comment (ingeridhellen) [inline packages/dm-core-plugins/src/form/fields/NumberField.test.tsx:195]:
```suggestion
      render(
```

File: packages/dm-core-plugins/src/form/fields/StringField.test.tsx [hunk 3]
```diff
@@ -240,18 +240,43 @@ describe('StringField', () => {
...
         },
       ])
+      let value = 'beep'
       const formData = {
-        foo: 'beep',
+        foo: value,
       }
-      render(<Form type="SingleField" formData={formData} />, { wrapper })
+
+      const { container } = render(
```
Comment (ingeridhellen) [inline packages/dm-core-plugins/src/form/fields/StringField.test.tsx:253]:
```suggestion
      render(
```

**Review by ingeridhellen — APPROVED** [review]
Looks good!

**Review by soofstad — APPROVED** [review]
