### PR TITLE
fix(attribute-selector): pass "onOpen" to views

### LINKED ISSUE #127: Form plugin wrapped in tabs needs improvement for arrays
#### Describe Problem
- Arrays appear both inside the home view, and as tabs for children. 
- not possible to close tabs, for children or array items.
- Cannot open children 
#### Suggest Solution
By default, arrays should only be shown as new tabs, and not as part of the home view. They are to be considered complex objects, even if the type of the array is simple. 
By default, the "form" view of the home should contain all simple attributed for editing, and provide actions, 
"open" for all required complex attributes, 
"remove" and "create" for all optional attributes, simple or complex. 

The "form" plugin needs additional options.
- List of children to be shown, and their related views. The default behaviour include all children, as described above. But this can be modified by specifically.
- option to open children in tabs, and provide a close bottom or not. Default is dictated by children type, and general option for opening them in tabs. 
- option to provide a desired list of actions to be added for complex children.  Default as described above.
- Improve the Array view to include two modes,
- - Giving list of attributes to view in a table. 
- - -Possibility to select and add from a list of "Actions"
- - Show each item in a separate drop-down segment, where the view could be selected using a UIRecipe.
-   
#### Additional Details

### PR DESCRIPTION
**Pull request by soofstad**
## What does this pull request change?
- Update "attribute-selector" plugin to pass "onOpen" to Views
- Update "form"-plugins ArrayField to not render lists of complex lists if "onOpen" is passed

## Why is this pull request needed?
- Changes to "view-concept" and "attribute-selector" caused "onOpen" to no longer function

## Issues related to this change
closes #127

### CODE REVIEW

File: packages/dm-core-plugins/src/attribute-selector/AttributeSelectorPlugin.tsx [hunk 1]
```diff
@@ -19,89 +19,89 @@ import {
...
+  const { idReference, config } = props
   const internalConfig: TAttributeSelectorConfig = {
     childTabsOnRender: true,
     asSidebar: false,
     items: [],
     ...config,
   }
   const [entity, isLoading, _, error] = useDocument<TGenericObject>(idReference)
-  const [selectedView, setSelectedView] = useState<number>(0)
+  const [selectedView, setSelectedView] = useState<string>()
```
Comment (KristianKjerstad) [inline packages/dm-core-plugins/src/attribute-selector/AttributeSelectorPlugin.tsx:30]: should this be initialized to empty string? Otherwise I think type is `string | undefined`

File: packages/dm-core-plugins/src/form/fields/ArrayField.tsx [hunk 2]
```diff
@@ -74,87 +68,41 @@ export default function Fields(props: any) {
...
-        <Button
-          variant="outlined"
-          data-testid={`add-${namePath}`}
-          onClick={() => {
-            handleAddObject()
-          }}
-        >
-          Add
-        </Button>
+        <OpenObjectButton namePath={`${namePath}`} />
```
Comment (KristianKjerstad) [inline packages/dm-core-plugins/src/form/fields/ArrayField.tsx:74]: props to this component is of type any, but I would assume the type for namePath is a string (?)

Then it would be equivalent to write
```
<OpenObjectButton namePath={namePath} />
```

**Review by KristianKjerstad — APPROVED** [review]
overall good!

Just 2 comments

File: packages/dm-core-plugins/src/attribute-selector/types.tsx [hunk 3]
```diff
@@ -10,7 +10,10 @@ export type TAttributeSelectorItem = {
   label?: string
 }
 export type TItemData = TAttributeSelectorItem & {
+  key: string
```
Comment (eoaksnes) [inline packages/dm-core-plugins/src/attribute-selector/types.tsx:13]: The`key` is a generic name, should it be renamed to viewId, itemId (or something like that)? Or, could the key be generated from the information that exists in the view config? Perhaps combine the name of the view config and the scope to get the unique key?

**Review by eoaksnes — APPROVED** [review]
Nice! Some comments to consider.

File: packages/dm-core-plugins/src/attribute-selector/AttributeSelectorPlugin.tsx (hunk 1 above)
Comment (soofstad) [reply packages/dm-core-plugins/src/attribute-selector/AttributeSelectorPlugin.tsx:30]: That is implicit typing for the "useState" with no initial value. But added explicitly now as well
