### PR TITLE
fix: update existing viewitem on add

### LINKED ISSUE #1065: fix(table): reorder the rows does not update the index used for tabs
Reordering the table does not change the index used for tabs, deleting or reordering.

Image

### PR DESCRIPTION
**Pull request by collinlokken**
## What does this pull request change?
Updates the tab (viewItem) with the latest state onOpen (e.g. with new index when position has changed after delete)

## Why is this pull request needed?
Opening tab after delete does not update the index

## Issues related to this change
Closes #1065

### CODE REVIEW

File: packages/dm-core-plugins/src/view_selector/useViewSelector.tsx [hunk 1]
```diff
@@ -52,19 +52,25 @@ export function useViewSelector(
...
-        rootEntityId: rootId || idReference,
-        onSubmit: onSubmitAdded,
-        onChange: onChangeAdded,
-        closeable: true,
-        isSubItem: isSubItem,
-      }
       setViewSelectorItems([...viewSelectorItems, newView])
+    } else {
+      newView.viewId = viewSelectorItems[existingViewIndex].viewId
+      viewSelectorItems[existingViewIndex] = newView
```
Comment (soofstad) [inline packages/dm-core-plugins/src/view_selector/useViewSelector.tsx:73]: How can this work, when you are not calling "setViewSelectorItems()"?

**Review by soofstad — CHANGES_REQUESTED** [review]

File: packages/dm-core-plugins/src/view_selector/useViewSelector.tsx (hunk 1 above)
Comment (collinlokken) [reply packages/dm-core-plugins/src/view_selector/useViewSelector.tsx:73]: It works, but mutating state is not recommended. Setting state again is better 👍

**Review by soofstad — APPROVED** [review]
