### PR TITLE
Fix/cleanup file plugin

### LINKED ISSUE #358: bug: employee app example not wokring. not able to fetch image

### PR DESCRIPTION
**Pull request by KristianKjerstad**
## What does this pull request change?
clean up the file plugin
- add type TFileEntity
- fix bug with extracting data source name from idReference in FilePlugin
- fix bug in form plugin with constructing link reference.

## Issues related to this change
closes #358

### CODE REVIEW

File: packages/dm-core-plugins/src/file/UploadFileButton.tsx [hunk 1]
```diff
@@ -1,23 +1,26 @@
...
+  splitAddress,
+  TLinkReference,
+  TStorageReference,
+  useDMSS,
+} from '@development-framework/dm-core'
 import { Button, Progress } from '@equinor/eds-core-react'
 import { AxiosError } from 'axios'
 import * as React from 'react'
 import { ChangeEvent, useEffect, useRef, useState } from 'react'
-import { useRegistryContext } from '../form/context/RegistryContext'
```
Comment (KristianKjerstad) [inline packages/dm-core-plugins/src/file/UploadFileButton.tsx:6]: using a registry from form plugin in the file plugin does not make sense... therefore It is removed and props to component are updated

File: packages/dm-core/src/types.ts [hunk 2]
```diff
@@ -132,6 +132,16 @@ export type TInlineRecipeViewConfig = TViewConfig & {
...
 }
 
+export type TFileEntity = {
+  type: string
+  name: string
+  author: string
+  date: string
+  size: number
+  filetype: string
+  content?: TLinkReference
```
Comment (ingeridhellen) [inline packages/dm-core/src/types.ts:142]: According to SIMOS/File.json, content has type "binary". Is that wrong?

**Review by ingeridhellen — APPROVED** [review]
Nice!

File: packages/dm-core-plugins/src/file/UploadFileButton.tsx (hunk 1 above)
Comment (ingeridhellen) [reply packages/dm-core-plugins/src/file/UploadFileButton.tsx:6]: Wouldn't that throw the `useRegistryContext must be used within a RegistryProvider` warning?

Comment (KristianKjerstad) [reply packages/dm-core-plugins/src/file/UploadFileButton.tsx:6]: it didnt seem to give any errors, but the value recieved from useRegistryContext() was sometimes empty

File: packages/dm-core/src/types.ts (hunk 2 above)
Comment (KristianKjerstad) [reply packages/dm-core/src/types.ts:142]: I was a bit confused by this. Since I don't know how the binary type is supposed to work (and I could not find any documentation about it), 

from some parts of dmss it looks like if type is "binary", it is interpreted as a storage reference.
image

However, from the implementation of the File plugin in dm-core-packages it looks like a link reference is required.
So I dont know if we should use link or storage reference for binary type.

we need to take another look at this once @eoaksnes  is back I think [(will add issue for this)](https://github.com/equinor/dm-core-packages/issues/403)

Comment (KristianKjerstad) [reply packages/dm-core/src/types.ts:142]: I did try to use a storage reference instead of a link reference in the File plugin, but could not make it work

Comment (ingeridhellen) [reply packages/dm-core/src/types.ts:142]: I don't know either. But I don't think it blocks this PR in any way, though. We can ask Eirik Ola next week

**Comment by KristianKjerstad** [comment]
https://github.com/equinor/data-modelling-storage-service/issues/484
