### PR TITLE
fix: allow no config for header plugin

### LINKED ISSUE #97: fix: optional config for "header"-plugin is not optional

### PR DESCRIPTION
**Pull request by KristianKjerstad**
## What does this pull request change?
allow no config for header plugin
## Issues related to this change
closes #97

### CODE REVIEW

File: packages/dm-core-plugins/src/header/HeaderPlugin.tsx [hunk 1]
```diff
@@ -41,14 +41,26 @@ type THeaderPluginConfig = {
...
 export default (props: IUIPlugin): JSX.Element => {
   const { idReference, config: passedConfig, type } = props
-  const config = passedConfig as THeaderPluginConfig
+  const config: THeaderPluginConfig = {
+    uiRecipesList:
+      passedConfig?.uiRecipesList ?? defaultHeaderPluginConfig.uiRecipesList,
+    hideUserInfo:
+      passedConfig?.hideUserInfo ?? defaultHeaderPluginConfig.hideUserInfo,
+    hideAbout: passedConfig?.hideAbout ?? defaultHeaderPluginConfig.hideAbout,
+  }
```
Comment (soofstad) [inline packages/dm-core-plugins/src/header/HeaderPlugin.tsx:63]:
```suggestion
  const config: THeaderPluginConfig = {...defaultHeaderPluginConfig, ..passedConfig}
```
