### PR TITLE
fix: loading bug in tree

### LINKED ISSUE #222: fix: add proper loading icon to tree view in dm-core-plugins

### PR DESCRIPTION
**Pull request by KristianKjerstad**
## What does this pull request change?
Before, the call to "expand tree" was buggy and did not do things in correct order. This issue is now fixed

Also, update some API calls that were wrong

## Issues related to this change
closes #222

### CODE REVIEW

File: packages/dm-core/src/domain/Tree.tsx [hunk 1]
```diff
@@ -209,51 +209,67 @@ export class TreeNode {
...
-          this.tree.index[this.dataSource].type = 'error'
-          this.tree.index[this.dataSource].message = error.message
-        })
-        .finally(() => {
-          this.tree.updateCallback(this.tree)
-        })
-    }
+  expand = () => {
+    return new Promise((resolve, reject) => {
+      ;(async () => {
```
Comment (ingeridhellen) [inline packages/dm-core/src/domain/Tree.tsx:214]: What syntax is this? Starting the line with `;`?

**Review by ingeridhellen — APPROVED** [review]
Nice!
