### PR TITLE
fix: add type for exported plugins from applications

### LINKED ISSUE #21: refactor(dm-core-package): rename EDmtPluginType to EPluginType and IDmtUiPlugin to IUiPlugin

### PR DESCRIPTION
**Pull request by KristianKjerstad**
## What does this pull request change?
add type
## Why is this pull request needed?
add type
## Issues related to this change

related to https://github.com/equinor/create-dm-app/issues/23
closes #21

### CODE REVIEW

**Review by netr0m — APPROVED** [review]
LGTM!

File: packages/dm-core/src/types.ts [hunk 1]
```diff
@@ -1,4 +1,6 @@
 import { JobStatus } from './services/api/configs/gen-job'
+import { EDmtPluginType } from './context/UiPluginContext'
```
Comment (soofstad) [inline packages/dm-core/src/types.ts:2]: Remove DMT name of type so this will also close issue #21

**Review by soofstad — APPROVED** [review]
