### PR TITLE
Fix/attribute selector recursiveness

### LINKED ISSUE #204: refactor: use yaml plugin as default for self when no attribute is specified in config
If not the plugin will go into forever...

### PR DESCRIPTION
**Pull request by soofstad**
## What does this pull request change?
- Set "yaml" as default plugin for "home" tab in "attribute-selector"
- Check for available docker-compose command in `example/reset-all.sh`
- Rename some test blueprints

## Why is this pull request needed?
- Avoid recursive "attribute-selector"
- Make `reset-all.sh` work with compose as a plugin
- Follow naming conventions
## Issues related to this change
closes #204

### CODE REVIEW

File: example/reset-all.sh [hunk 1]
```diff
@@ -1,7 +1,16 @@
 #!/usr/bin/env bash
 set -e
-docker-compose run --rm dmss reset-app
-docker-compose run --rm job-api dm -u http://dmss:5000 reset ../app
+
+# Get the available docker-compose command
```
Comment (KristianKjerstad) [inline example/reset-all.sh:4]: cool!

**Review by KristianKjerstad — APPROVED** [review]
looks good!
