### PR TITLE
fix: default tab name on open

### LINKED ISSUE #860: feat(view creator): If the element does not have a name, then show the index.

### PR DESCRIPTION
**Pull request by collinlokken**
## What does this pull request change?
Use index and attribute name when opening object without name in new tab

## Why is this pull request needed?
Name is often not a required attribute

## Issues related to this change
Close #860

### CODE REVIEW

File: packages/dm-core-plugins/src/list/ListPlugin.tsx [hunk 1]
```diff
@@ -108,7 +108,12 @@ export const ListPlugin = (props: IUIPlugin & { config?: TListConfig }) => {
       return
     }
 
-    const view = { ...internalConfig.openViewConfig, label: item?.data?.name }
+    const view = {
+      ...internalConfig.openViewConfig,
+      label: item?.data?.name
+        ? item?.data?.name
+        : `${attribute?.name} #${item.index}`,
```
Comment (henrikbossart) [inline packages/dm-core-plugins/src/list/ListPlugin.tsx:115]: I think this can be simplified to this?
```suggestion
      label: item?.data?.name ?? `${attribute?.name} #${item.index}`,
```

File: packages/dm-core/src/components/Table/TableRow/TableRow.tsx [hunk 2]
```diff
@@ -40,7 +40,12 @@ export function TableRow(props: TableRowProps) {
   function openItemAsTab() {
     props.onOpen(
       crypto.randomUUID(),
-      { label: item?.data?.name, type: 'ViewConfig' },
+      {
+        label: item?.data?.name
+          ? item?.data?.name
+          : `${idReference.split('.').slice(-1)} #${item.index}`,
```
Comment (henrikbossart) [inline packages/dm-core/src/components/Table/TableRow/TableRow.tsx:46]: Same as above
```suggestion
        label: item?.data?.name ?? `${idReference.split('.').slice(-1)} #${item.index}`,
```

File: packages/dm-core-plugins/src/list/ListPlugin.tsx (hunk 1 above)
Comment (collinlokken) [reply packages/dm-core-plugins/src/list/ListPlugin.tsx:115]: Agreed! 👍

**Review by eoaksnes — APPROVED** [review]
