### PR TITLE
fix(job): use check document existence endpoint to verify job

### LINKED ISSUE #437: fix(job): can't start signalApp job
#### Actual Behaviour

Raises exception 400 bad request. 

#### Steps to Reproduce

- Open the example application
- Go to signalApp
- Open case1
- Push the create button for the job

### PR DESCRIPTION
**Pull request by collinlokken**
## What does this pull request change?
Introduces a check that verifies the existence of the job before it is attempted updated. The documentAdd endpoint will be used instead if the job does not exist.

## Why is this pull request needed?
The check removes an error in the client, produced by the fact that a non-existent job is attempted updated.

## Issues related to this change
Closes #437

### CODE REVIEW

File: example/src/plugins/job-ui-single/pages/CreateJobEntity.tsx [hunk 1]
```diff
@@ -54,31 +51,63 @@ export const CreateJobEntity = (props: TCreateJobEntityProps) => {
...
+      if (jobExists) {
+        updateDocument(jobEntityDestination, jobEntityFormData)
+      } else {
+        addDocument(jobEntityDestination, jobEntityFormData)
+      }
+    }
+
+    // TODO: Implement document check
+    DmssApi.documentCheck({
+      address: jobEntityDestination,
```
Comment (ingeridhellen) [inline example/src/plugins/job-ui-single/pages/CreateJobEntity.tsx:103]: Can the address point to a list? In that case, we should use addDocument even if the list exist, I think

**Review by ingeridhellen — APPROVED** [review]
