### PR TITLE
fix: content of sidebar now fills available space

### LINKED ISSUE #148: fix(attribute-sidebar): width of content does not use all available space

### PR DESCRIPTION
**Pull request by soofstad**
## What does this pull request change?
- set CSS prop "fill-available" on some wrappers

## Why is this pull request needed?
- some plugins were being squashed

Before:
Screenshot_20230314_091639

After:
Screenshot_20230314_091703

## Issues related to this change
closes #148

### CODE REVIEW

File: packages/dm-core-plugins/src/attribute-selector/AttributeSelectorPlugin.tsx [hunk 1]
```diff
@@ -90,6 +90,7 @@ export const AttributeSelectorPlugin = (props: IUIPlugin): JSX.Element => {
         style={{
           display: 'flex',
           flexDirection: config.asSidebar ? 'row' : 'column',
+          width: '-webkit-fill-available',
```
Comment (ingeridhellen) [inline packages/dm-core-plugins/src/attribute-selector/AttributeSelectorPlugin.tsx:93]:
```suggestion
```

File: packages/dm-core-plugins/src/attribute-selector/Content.tsx [hunk 2]
```diff
@@ -11,6 +11,7 @@ import { TChildTab } from './AttributeSelectorPlugin'
 const HidableWrapper = styled.div<any>`
   display: ${(props: { hidden: boolean }) => (props.hidden && 'none') || 'flex'}
   align-self: normal;
+  width: -webkit-fill-available;
```
Comment (ingeridhellen) [inline packages/dm-core-plugins/src/attribute-selector/Content.tsx:14]:
```suggestion
  width: 100%;
```

File: packages/dm-core-plugins/src/attribute-selector/Content.tsx [hunk 3]
```diff
@@ -26,7 +27,7 @@ export const Content = (): JSX.Element => {
     config,
   } = useTabContext()
   return (
-    <>
+    <div style={{ width: '-webkit-fill-available' }}>
```
Comment (ingeridhellen) [inline packages/dm-core-plugins/src/attribute-selector/Content.tsx:30]:
```suggestion
    <div style={{ width: '100%' }}>
```

**Review by ingeridhellen — CHANGES_REQUESTED** [review]
Have you tested multiple browsers? I believe -webkit-fill-available only works on some browsers. I would instead like you to do the below fixes

File: packages/dm-core-plugins/src/attribute-selector/AttributeSelectorPlugin.tsx (hunk 1 above)
Comment (soofstad) [reply packages/dm-core-plugins/src/attribute-selector/AttributeSelectorPlugin.tsx:93]: This one is needed. If not, the "fill avilable" only effects the first level of the sidebar (if they are nested).
But "100%" works on chrome and firefox :+1:

**Review by ingeridhellen — APPROVED** [review]
