### PR TITLE
fix(jobPlugin): multiple issues with jobPlugin

### LINKED ISSUE #647: bug(JobPlugin): Wrong address inserted into jobAddress in JobPlugin
Wrong address inserted into jobAddress in JobPlugin

### PR DESCRIPTION
**Pull request by soofstad**
## What does this pull request change?
- Some refactoring and code cleanup
- JobControlButton now correctly show proper action that the user can take
- JobControlButton no longer remove jobs
-  'useDocument's update function is now async, with a "notify" parameter
- "useJob" now ties the status interval with the "jobHookId"

## Why is this pull request needed?
- Fixes multiple bugs with "useJob" and JobPugin

## Issues related to this change

closes #647

### CODE REVIEW

**Comment by henrikbossart** [comment]
This is not working for me. It fails to get the job attribute.
```
{
  "status": 404,
  "type": "NotFoundException",
  "message": "Failed to get document referenced with 'dmss://DemoDataSource/$4483c9b0-d505-46c9-a157-94c79f4d7a6a.study.cases[0].job'",
  "debug": "Invalid attribute 'job'. Valid attributes are '['name', 'type', 'description', 'duration', 'timeStep', 'components', 'signal']'.. The requested resource could not be found",
  "data": null
}


```

File: packages/dm-core-plugins/src/job/JobControlButton.tsx [hunk 1]
```diff
@@ -1,53 +1,57 @@
...
-      if (!jobExists) {
-        createJob().then(() => {
-          start()
-        })
-      } else {
-        start()
-      }
-    }
+  function handleClick() {
+    if (!jobExists) return createJob().then(() => start())
```
Comment (collinlokken) [inline packages/dm-core-plugins/src/job/JobControlButton.tsx:19]: `createJob` allready handles `jobExists`, and either updates or creates new. Right now it is not possible to update the job if it already exist. handleClick should just call `createJob` then `start`

File: packages/dm-core-plugins/src/job/JobPlugin.tsx [hunk 2]
```diff
@@ -90,86 +87,34 @@ export const JobPlugin = (props: IUIPlugin & { config: JobPluginConfig }) => {
...
-        setJobExists(true)
-      })
-    }
-  }, [jobEntityId])
-
   function createNewJob(): Promise<unknown> {
-    setAllowJobStart(true)
     if (jobExists) {
-      return updateDocument(jobTargetAddress(), jobEntity)
+      return updateDocument(jobEntity, false).then(() => setJobExists(true))
```
Comment (collinlokken) [inline packages/dm-core-plugins/src/job/JobPlugin.tsx:108]: Do we need to setJobExistst -> true here?  It is already inside the `if...` because `jobExists`

File: packages/dm-core-plugins/src/job/JobPlugin.tsx [hunk 3]
```diff
@@ -44,43 +45,39 @@ export const JobPlugin = (props: IUIPlugin & { config: JobPluginConfig }) => {
...
-    start,
-    error,
-    fetchResult,
-    fetchStatusAndLogs,
-    logs,
-    status,
-    remove,
-  } = useJob(jobEntityId, jobId)
+    document: jobDocument,
+    isLoading,
```
Comment (collinlokken) [inline packages/dm-core-plugins/src/job/JobPlugin.tsx:74]: `isLoading: bool`

**Review by collinlokken — CHANGES_REQUESTED** [review]
Nice! With some comments :)

File: packages/dm-core-plugins/src/job/JobPlugin.tsx (hunk 3 above)
Comment (henrikbossart) [reply packages/dm-core-plugins/src/job/JobPlugin.tsx:74]: not really needed? and the type would be `Boolean` ;)

**Comment by soofstad** [comment]
@henrikbossart Yes that was showing for 1sec before it continued.
Fixed it by resetting error in useJob :+1:

**Review by henrikbossart — APPROVED** [review]
:+1:

**Review by collinlokken — APPROVED** [review]
Nice
