### PR TITLE
fix: select entity label as view label

### LINKED ISSUE #1064: fix(table, list): correct order of defaults when indexing
The naming does not use the correct order of defaults when indexing:
If indexing is enabled, i.e. labelByIndex true, the order of label should be 1) label inside Viewconfig, 2)label inside the entity, 3)name inside the entity, 4)list attribute name

### PR DESCRIPTION
**Pull request by collinlokken**
## What does this pull request change?
Prioritieses entitty label above enity name when generating label for viewSelectorItem

## Why is this pull request needed?
Requested feature

## Issues related to this change
Closes #1064

### CODE REVIEW

File: packages/dm-core-plugins/src/list/ListPlugin.tsx [hunk 1]
```diff
@@ -152,9 +152,11 @@ export const ListPlugin = (props: IUIPlugin & { config?: TListConfig }) => {
...
     const label = config.label
       ? config.label
-      : item?.data?.name
-        ? item?.data?.name
-        : `${attribute?.name}`
+      : item?.data?.label
+        ? item?.data?.label
+        : item?.data?.name
+          ? item?.data?.name
+          : `${attribute?.name}`
```
Comment (soofstad) [inline packages/dm-core-plugins/src/list/ListPlugin.tsx:159]: Shorten with "||" instead of " ? :"?

**Review by soofstad — CHANGES_REQUESTED** [review]

**Review by soofstad — APPROVED** [review]
