### PR TITLE
fix: use form state to update entity

### LINKED ISSUE #1073: bug(primitive-array): some indexing error.
See video: 
https://jam.dev/c/18c2a7a4-1a82-483a-997c-d84ea14237be

Steps to reproduce:
- Add two new rows
- Populate one with data
- Submit and get required-error
- Remove the one with error
- Submit again.

### PR DESCRIPTION
**Pull request by collinlokken**
## What does this pull request change?
Use react hook from context to manipulate form state when deleting item in primitive array

## Why is this pull request needed?
Bug where primitive array is not updated correctly when deleting while in dirty state

## Issues related to this change
Closes #1073

### CODE REVIEW

File: packages/dm-core-plugins/src/form/components/PrimitiveArray.tsx [hunk 1]
```diff
@@ -39,7 +39,7 @@ const PrimitiveArray = ({
   const { getValues } = useFormContext()
 
   const updateValues = (index: number, newValue: TPrimitive): void => {
-    const newValues = [...getValues(namePath)]
+    const newValues = getValues(namePath) ? getValues(namePath) : []
```
Comment (awesthouse) [inline packages/dm-core-plugins/src/form/components/PrimitiveArray.tsx:42]: Pretty sure this should still be a copy, no? We're still modifying the array directly.
Also, shorthand `getValues(namepath) || []`? 🙂

File: packages/dm-core-plugins/src/form/components/PrimitiveArray.tsx [hunk 2]
```diff
@@ -55,7 +55,7 @@ const PrimitiveArray = ({
     }
   }
   const removeItem = (index: number) => {
-    const newValues = [...getValues(namePath)]
+    const newValues = getValues(namePath) ? getValues(namePath) : []
```
Comment (awesthouse) [inline packages/dm-core-plugins/src/form/components/PrimitiveArray.tsx:58]: Same as comment in updateValues function

File: packages/dm-core-plugins/src/form/components/PrimitiveArray.tsx (hunk 1 above)
Comment (collinlokken) [reply packages/dm-core-plugins/src/form/components/PrimitiveArray.tsx:42]: Will apply the shorthand 👍 
Modifying the return value of getValues does not cause a re-render, so it is not necessary to perform a deep copy.

**Review by awesthouse — APPROVED** [review]
🎉
